---
# frontend/tasks/main.yml

- name: Install Node.js
  apt:
    name: nodejs
    state: present
  become: yes

- name: Install npm
  apt:
    name: npm
    state: present
  become: yes

- name: Clone the frontend repository
  git:
    repo: 'https://github.com/your-username/your-repo.git'
    dest: /home/ubuntu/frontend
    version: 'main'
  become: yes

- name: Install dependencies for the frontend
  command: npm install
  args:
    chdir: /home/ubuntu/frontend
  become: yes

- name: Start the frontend application
  command: npm start
  args:
    chdir: /home/ubuntu/frontend
  become: yes

