- hosts: database_servers
  become: yes
  tasks:
    - name: Install MongoDB
      apt:
        name: mongodb
        state: present

    - name: Start MongoDB service
      service:
        name: mongodb
        state: started
        enabled: yes

    - name: Create MongoDB database and user
      command: mongo admin --eval "db.createUser({user: 'mernuser', pwd: 'securepassword', roles: [{role: 'readWrite', db: 'mern'}]})"

